### ISSUE TITLE
一加系列不能解锁了

### ISSUE THREAD

**Issue by xxnuo** [KHwang9883/MobileModels#148]
https://b23.tv/DjSOEZp

**Comment by KHwang9883** [comment]
https://t.me/MlgmXyysd_bibilailai/1876

**Comment by MlgmXyysd** [comment]
https://t.me/MlgmXyysd_bibilailai/1881

**Comment by xxnuo** [comment]
https://www.v2ex.com/t/1070548

**Comment by MlgmXyysd** [comment]
> https://www.v2ex.com/t/1070548

这种一眼丁真的帖子就别发了。。早都说了客服是知识库固定话术，回答的是oddo新机不开深度测试的事
