### ISSUE TITLE
能否增加手机的价格

### ISSUE THREAD

**Issue by xinggit** [KHwang9883/MobileModels#16]
手机型号的一大作用是找出用户的手机价格区间，作为一个消费特征，确定用户的价值，请问一下作者后续是否有计划加上手机价格/区间？

**Comment by KHwang9883** [comment]
无此类计划，本项目侧重汇总手机宣传名、认证型号（以及部分品牌 codename）的对应关系，暂不加入价格信息。可以参考某些门户网站的数据库或者《手机性能排行》这款 app，它们更加侧重收集手机配置参数（包括价格），同时也有对比功能

**Comment by xinggit** [comment]
OK, best wish to you
