### ISSUE TITLE
Hi 小米黑鲨手机型号更改

### ISSUE THREAD

**Issue by Haloka** [KHwang9883/MobileModels#19]
小米黑鲨手机型号从useragent取出的是  『SHARK KLE-A0』， 
而型号列表中的是  KLE-A0: 腾讯黑鲨游戏手机 3S 全网通版，
麻烦修正下呀。

黑鲨手机需要订正的有以下几个国内版型号：

「MBU-A0」修改为「SHARK MBU-A0」
「MBU-A0」修改为「SHARK MBU-A0」
「KLE-A0」修改为「SHARK KLE-A0」
「PRS-A0」修改为「SHARK PRS-A0」
「KSR-A0」修改为「SHARK KSR-A0」

![image](https://user-images.githubusercontent.com/29751822/121625962-15dbaf00-caa7-11eb-866a-9c7c19009978.png)

**Comment by KHwang9883** [comment]
已修复
