### ISSUE TITLE
华为 MatePad 11 参数补充

### ISSUE THREAD

**Issue by People-11** [KHwang9883/MobileModels#25]
直接从DevCheck获取的参数：
Model：DBY-W09
Product：DBY-W09
Device：HWDBY
Board：DBY
Manufacturer：HUAWEI

**Comment by KHwang9883** [comment]
这个 `HWDBY` 不是设备实际的 codename，目前我没查到

**Comment by People-11** [comment]
> 这个 `HWDBY` 不是设备实际的 codename，目前我没查到

我也没查到，所以就直接去华为店看了

**Comment by KHwang9883** [comment]
已增补
