### ISSUE TITLE
求解：大神 哪里能有苹果手机的前几位imei和机型对照表

### ISSUE THREAD

**Issue by anning666** [KHwang9883/MobileModels#3]

**Comment by KHwang9883** [comment]
型号汇总只负责整理机型型号与宣传名（包括部分机型 codename）的对应关系，我没研究过 iPhone 的 IMEI，所以很抱歉这里没有这种对照表。

**Comment by anning666** [comment]
> 型号汇总只负责整理机型型号与宣传名（包括部分品牌机型 codename）的对应关系，我没研究过 iPhone 的 IMEI，所以很抱歉这里没有这种对照表。

OK好的 我也只是试着问一下 ，你的这个对应表做得很好 👍
