### ISSUE TITLE
一加型号

### ISSUE THREAD

**Issue by KHwang9883** [KHwang9883/MobileModels#42]
![图片](https://user-images.githubusercontent.com/44646371/169649591-98446c21-b5d8-4e0d-ac38-8a257dbff5dc.png)

**Comment by ZhouYixun** [comment]
1. CPH2411 -> ONEPLUS 10R 5G海外版
2. PGKM10 -> ONEPLUS Ace中国版
3. CPH2423 -> ONEPLUS 10R 5G印度版

**Comment by KHwang9883** [comment]
> 1. CPH2411 -> ONEPLUS 10R 5G海外版
> 
>     2. PGKM10 -> ONEPLUS Ace中国版
> 
>     3. CPH2423 -> ONEPLUS 10R 5G印度版
> 
> 
> 搜的材料，准确度未知，希望帮到您

十分感谢，看了下提交历史，发现是我 google 的时候搞错了。。

**Comment by sanchezzzhak** [comment]
CPH2411  NEPLUS 10R 5G
PGKM10  OnePlus Ace 5G  http://zd.taf.org.cn/#/equipmentDetail?code=H49SvJYjVe7X%2B5NUgd40vxyjC2DN7rOmvz%2FFnxf1yPHmWm0HOCxN8NDdHk%2FPSWKy
CPH2423 OnePlus 10R 5G
