### ISSUE TITLE
内部型号新增

### ISSUE THREAD

**Issue by Drew233** [KHwang9883/MobileModels#46]
你好，我统计了一部分仓库中当前不存在的内部型号，希望有空可以合并进去
bmh-an10,HONOR 30
cdy-an00,HUAWEI nova 7 SE
cdy-an90,HONOR 30s
jad-al50,HUAWEI P50 Pro
jef-an00,HUAWEI nova 7 5G
jer-an10,HUAWEI nova 7 Pro
noh-an00,HUAWEI Mate 40 Pro
noh-an01,HUAWEI Mate 40 Pro 5G
tel-an00,HONOR X10
tel-an10,HONOR X10
V2217A,iQOO 10
HLK-AL00,HONOR 9X

**Comment by soyadios** [comment]
> 你好，我统计了一部分仓库中当前不存在的内部型号，希望有空可以合并进去 bmh-an10,HONOR 30 cdy-an00,HUAWEI nova 7 SE cdy-an90,HONOR 30s jad-al50,HUAWEI P50 Pro jef-an00,HUAWEI nova 7 5G jer-an10,HUAWEI nova 7 Pro noh-an00,HUAWEI Mate 40 Pro noh-an01,HUAWEI Mate 40 Pro 5G tel-an00,HONOR X10 tel-an10,HONOR X10 V2217A,iQOO 10 HLK-AL00,HONOR 9X

it is very cool

**Comment by KHwang9883** [comment]
这些型号我看了下都是存在的，应该是因为我并列了这些型号导致的漏统计？

**Comment by KHwang9883** [comment]
也可能是外部抓取时遇到这种情况会漏掉，应该不是这边的问题
