### ISSUE TITLE
Huawei BLM-00

### ISSUE THREAD

**Issue by sanchezzzhak** [KHwang9883/MobileModels#61]
Hi
it seems like it would be a mistake to treat this as a TV
![image](https://user-images.githubusercontent.com/1337066/219050754-8f76bc3d-894c-42ce-973e-c9a998e83969.png)

UA: Mozilla/5.0 (Linux; U; Android 10; zh-CN; BLM-00 Build/HUAWEIBLM-00) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 UWS/3.22.1.228 Mobile Safari/537.36 AliApp(DingTalk/6.5.30) com.alibaba.android.rimet/25293052 Channel/227200 language/zh-CN abi/64 Pad/APad Hmos/1 UT4Aplus/0.2.25 colorScheme/light
model:  BLM-00
OS: HarmonyOS
Version: 1.0.0
prefix for UA Pad/APad - Tablet

https://product.suning.com/0000000000/12304515464.html

**Comment by KHwang9883** [comment]
If identified word "智慧屏" then the device type will be tv
The script generating csv file does have some problems, including what you didn't mention. It is not written by me, and I can't fix

**Comment by KHwang9883** [comment]
> If identified word "智慧屏" then the device type will be tv The script generating csv file does have some problems, including what you didn't mention. It is not written by me, and I can't fix

@anyongjin 问题包括但不限于下图所示

![图片](https://user-images.githubusercontent.com/44646371/219070605-4f8dbd7a-b39f-4931-bae4-18bf860ddde1.png)
![图片](https://user-images.githubusercontent.com/44646371/219070877-c36bd445-3b16-4af2-b797-f6d56e99892e.png)
![图片](https://user-images.githubusercontent.com/44646371/219071473-d1c2a52c-4127-4afd-a498-9d1a86784065.png)

**Comment by anyongjin** [comment]
【BLM-00问题】
由于文档中绝大部分使用了“智慧屏”的都是电视，所以脚本中将“智慧屏”作为电视的特征了。
[这个Issue](https://github.com/KHwang9883/MobileModels/issues/61)中提到的“BLM-00”确实是一个平板电脑，并不是电视，也使用了“智慧屏”。
脚本在检测设备时有尝试检测“Pad”或“平板”等特征，会作为“pad”类型。
设备类型字段会尝试从一级标题、二级标题、加粗行中提取。任意一级提取到就会更新。
所以为避免特征词歧义，以及脚本逻辑过度复杂，最好的方案还是在加粗行中指明这是一个Pad，而非电视。
【华为早期产品，手机识别为tv】
下面的“华为早期产品”全部都是手机，也因为没有手机的特征词，全部使用了前面检测到的tv。
故将“华为早期产品”改为“华为早期手机产品”后，重新运行脚本，问题解决。
【版本前面有1#】
个别型号的版本名称前面有“#”，这表示**型号名称**是**版本名称**的前缀，所以为避免冗余，将版本名称简化了，以“#”开头。
个别型号的版本名称除了有“#”，前面还有“1”，这表示这个设备编号对应了多个型号名称，而对应的版本名称的前缀不是第1个，而是第二个。所以在“#”前面加了索引“1”
