### ISSUE TITLE
华为保时捷更新

### ISSUE THREAD

**Issue by orca-zhang** [KHwang9883/MobileModels#62]
HUAWEI Mate 40 RS 保时捷设计:

NOP-AN00P: HUAWEI Mate 40 RS 保时捷设计

HUAWEI Mate 50 RS 保时捷设计:

DCO-AL00P: HUAWEI Mate 50 RS 保时捷设计

结尾需要加P

**Comment by KHwang9883** [comment]
我看华为官网写的不带 P 啊
![图片](https://user-images.githubusercontent.com/44646371/220035273-9efb96af-cf20-42a5-a81a-ddb4de89d171.png)
![图片](https://user-images.githubusercontent.com/44646371/220035300-e6e2ff6f-0b38-4dfc-afe9-93e50330574c.png)

**Comment by orca-zhang** [comment]
"type":"device"
		"usb":"338952192X"
		"product":"NOP-AN00P"
		"model":"NOP_AN00"
		"device":"HWNOP"

**Comment by KHwang9883** [comment]
> 		"type":"device"
> 		"usb":"338952192X"
> 		"product":"NOP-AN00P"
> 		"model":"NOP_AN00"
> 		"device":"HWNOP"

还是以入网型号为准
