### ISSUE TITLE
Mi CC 9/9e codenames

### ISSUE THREAD

**Issue by yshalsager** [KHwang9883/MobileModels#7]
Hi, Here're the new devices codenames
Mi CC9 - F3B - PYXIS - http://bigota.d.miui.com/V10.3.5.0.PFCCNXM/miui_PYXIS_V10.3.5.0.PFCCNXM_224960eda9_9.0.zip
Mi CC9e - F9S - LAURUS - no Public ROMs yet
Mi CC9 Meitu Edition - F3M - VELA - http://bigota.d.miui.com/V10.3.1.0.PFECNXM/miui_VELA_V10.3.1.0.PFECNXM_215f256089_9.0.zip

I didn't find any way to contact you so I made this issue :)

**Comment by KHwang9883** [comment]
Added.
