### ISSUE TITLE
有些信息是不是不正确？

### ISSUE THREAD

**Issue by Oreo1995** [KHwang9883/MobileModels#70]
比如：
华为P60 Pro和P60 Art的信息是相同的？
华为Mate50 Pro和Mate50 RS保时捷设计的信息是相同的？

有个疑问：如果信息都一样，那第三方APP又是怎么识别P60 Pro和P60 Art的呢？

**Comment by KHwang9883** [comment]
它们的入网型号是相同的，不是错误
第三方 App 可能读取的是 `build.prop` 中的其他信息，其中包含的不止有型号，应该可以区分

**Comment by Oreo1995** [comment]
原来如此，谢谢
