### ISSUE TITLE
建议启用Github Pages

### ISSUE THREAD

**Issue by Jesse205** [KHwang9883/MobileModels#72]
由于中国访问Github可能会出现无法访问的情况，而且还可以拥有沉浸式的阅读体验，因此使用GithubPages为最棒的选择。

**Comment by KHwang9883** [comment]
GitHub Pages 也可能无法访问。我之前同步了一个 Gitee 库：https://gitee.com/newlife2017/MobileModels

**Comment by KHwang9883** [comment]
https://khwang9883.github.io/MobileModels/
先凑合看吧
