### ISSUE TITLE
保存的csv型号名称缺失 "+"

### ISSUE THREAD

**Issue by dalangll** [KHwang9883/MobileModels#73]
所有实际型号名包含"+"的都过滤了"+"

**Comment by KHwang9883** [comment]
@anyongjin

**Comment by KHwang9883** [comment]
py 脚本不是我写的，我也不知道怎么改，脚本原作者疑似已删号

**Comment by dalangll** [comment]
> > py 脚本不是我写的，我也不知道怎么改，脚本原作者疑似已删号
> 
> 好的 我来改改
将29行改为
`_re_char = re.compile(r'[a-zA-Z0-9_+]')`

**Comment by KHwang9883** [comment]
> > > py 脚本不是我写的，我也不知道怎么改，脚本原作者疑似已删号
> > 
> > 
> > 好的 我来改改
> > 将29行改为
> > `_re_char = re.compile(r'[a-zA-Z0-9_+]')`

这样写有点问题，我改了下应该 + 号都有了
