### ISSUE TITLE
Several codenames for Huawei & Honor

### ISSUE THREAD

**Issue by zhaozihanzzh** [KHwang9883/MobileModels#8]
荣耀畅玩 4C：cherry mini （华为官网曾经有以Cherry Mini 为文件名的内核源码包）
华为 P8 青春版（海外HUAWEI P8 Lite）：alice（https://forum.xda-developers.com/p8lite/development/rom-t3606568/post72289795）
荣耀 V8：knight（https://www.sohu.com/a/70667447_406681）
华为 Mate 9：manhattan（https://www.sohu.com/a/116101470_118778）

**Comment by zhaozihanzzh** [comment]
华为 Mate 9 Pro：long land（https://m.sohu.com/a/116101470_118778/?pvid=000115_3w_a）
荣耀 4A：Scale（HUAWEI Y6）（https://github.com/Thespartann/android_device_huawei_scale）

**Comment by KHwang9883** [comment]
已添加

**Comment by zhaozihanzzh** [comment]
荣耀 9X：hulk （https://xw.qq.com/digi_tech/20190716000512/DIG2019071600051200）

**Comment by KHwang9883** [comment]
已添加
