### ISSUE TITLE
大神，求救

### ISSUE THREAD

**Issue by jowekn** [KHwang9883/MobileModels#80]
Error
Looks like something went wrong
打开一直出现这个错误，是什么原因，能不能帮我解决下，大神，这个数据对我很重要
![Uploading S31020-23421389_com.android.browser.png…]()

**Comment by KHwang9883** [comment]
你图没发出来

**Comment by jowekn** [comment]
https://github.com/KHwang9883/MobileModels/blob/master/brands/xiaomi.md
大神，这个网址打开一直显示错误，是什么原因，之前不会的

**Comment by jowekn** [comment]
我很需要里面的小米手机型号数据，大神，求求你帮帮忙

**Comment by KHwang9883** [comment]
> https://github.com/KHwang9883/MobileModels/blob/master/brands/xiaomi.md 大神，这个网址打开一直显示错误，是什么原因，之前不会的

我这边没任何问题，可以尝试这个链接：https://khwang9883.github.io/MobileModels/brands/xiaomi.html

**Comment by jowekn** [comment]
可以了，换个链接就可以了，谢谢了，大神
