### ISSUE TITLE
360 手机解锁实际情况与登记不符

### ISSUE THREAD

**Issue by xxxxxliil** [KHwang9883/MobileModels#89]
360 /奇酷手机从未~~实装~~公开解锁申请渠道。N4 系列的解锁都是靠 N4 初始（1.0.019）版本的 bootloader 忘记限制解锁能力，于是 N4s MTK 版恰好因为 Soc 与 N4 一样解锁所以可以刷 N4 的 lk 去解锁。

**Comment by KHwang9883** [comment]
这个情况需要写进备注吗

**Comment by xxxxxliil** [comment]
> 这个情况需要写进备注吗

我正在写

**Comment by KHwang9883** [comment]
> > 这个情况需要写进备注吗
> 
> ~我正在写~被抢先了
> 
> 有没有第三方解锁的标注呢？因为标注不能解锁，但是实际上可以，这种事情有点尴尬

#86 
- 不提倡使用第三方解锁服务（通常是因为容易遇到网络诈骗），去除所有“可使用第三方服务解锁”的备注，对于仅能通过第三方解锁服务的品牌，标记为“不可解锁 BootLoader”

之前有，后来删了

**Comment by xxxxxliil** [comment]
> > > 这个情况需要写进备注吗
> > 
> > 
> > ~我正在写~被抢先了
> > 有没有第三方解锁的标注呢？因为标注不能解锁，但是实际上可以，这种事情有点尴尬
> 
> #86
> 
> * 不提倡使用第三方解锁服务（通常是因为容易遇到网络诈骗），去除所有“可使用第三方服务解锁”的备注，对于仅能通过第三方解锁服务的品牌，标记为“不可解锁 BootLoader”
> 
> 之前有，后来删了

应该把标题改成“官方支持的解锁/内核源码/解后保修”，避免有人看到标题后认为特定品牌毫无可能解锁

**Comment by xxxxxliil** [comment]
@KHwang9883 可以再来看一下吗？
