### ISSUE TITLE
这个是不是有错？

### ISSUE THREAD

**Issue by lenglqy** [KHwang9883/MobileModels#98]
![Screenshot_2023-12-08-14-14-31-917_com.github.android.jpg](https://github.com/KHwang9883/MobileModels/assets/101696117/532b5d04-6251-45d6-96c4-dfd912e6f66a)

小米不是解锁bl也有保修吗

**Comment by MlgmXyysd** [comment]
小米官方已在解锁工具的免责条款中，以及各延保服务的条款中声明解锁或刷机后失去保修资格，这些声明均具有法律效力。有人说售后实际执行可以保修，但并未找到明文规定。信息公开应以有法律效力的明文规定为准。
